name: FloatingByPeaga

options:
  bundleIdPrefix: com.phzin

targets:
  FloatingByPeaga:
    type: application
    platform: iOS
    deploymentTarget: "15.0"

    sources:
      - path: .
        excludes:
          - .github
          - project.yml
          - README.md
          - "*.ipa"

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.phzin.FloatingByPeaga
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: 5.0

    info:
      path: Info.plist
