name: Build FloatingByPeaga

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar XcodeGen
        run: brew install xcodegen

      - name: Criar projeto Xcode
        run: xcodegen generate

      - name: Compilar App
        run: |
          xcodebuild \
            -project FloatingByPeaga.xcodeproj \
            -scheme FloatingByPeaga \
            -sdk iphoneos \
            -configuration Release \
            -derivedDataPath build \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Criar IPA corretamente
        run: |
          APP_PATH=$(find build/Build/Products/Release-iphoneos -type d -name "*.app" | head -n 1)

          echo "App encontrado:"
          echo "$APP_PATH"

          rm -rf Payload
          rm -f FloatingByPeaga.ipa

          mkdir -p Payload
          cp -R "$APP_PATH" Payload/

          ditto -c -k --sequesterRsrc --keepParent Payload FloatingByPeaga.ipa

          echo "===== TESTANDO ====="
          unzip -t FloatingByPeaga.ipa

          echo "===== ESTRUTURA ====="
          unzip -l FloatingByPeaga.ipa

          echo "===== TIPO DO ARQUIVO ====="
          file FloatingByPeaga.ipa

          echo "===== INFO.PLIST ====="
          plutil -p Payload/FloatingByPeaga.app/Info.plist

          echo "===== TAMANHO ====="
          ls -lh FloatingByPeaga.ipa

          echo "===== SHA256 ====="
          shasum -a 256 FloatingByPeaga.ipa

      - name: Enviar IPA
        uses: actions/upload-artifact@v4
        with:
          name: FloatingByPeaga-IPA
          path: FloatingByPeaga.ipa
          if-no-files-found: error
