name: Build FloatingByPeaga

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Instalar XcodeGen
        run: brew install xcodegen

      - name: Criar projeto Xcode
        run: xcodegen generate

      - name: Compilar para iPhone
        run: |
          xcodebuild \
            -project FloatingByPeaga.xcodeproj \
            -scheme FloatingByPeaga \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Criar IPA
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -path "*/Build/Products/Release-iphoneos/FloatingByPeaga.app" -type d | head -n 1)

          echo "=== APP ENCONTRADO ==="
          echo "$APP_PATH"

          echo "=== CONTEÚDO DO APP ==="
          ls -lah "$APP_PATH"

          mkdir -p Payload
          cp -R "$APP_PATH" Payload/

          echo "=== CRIANDO IPA ==="
          /usr/bin/zip -r -y FloatingByPeaga.ipa Payload

          echo "=== VERIFICANDO IPA ==="
          unzip -l FloatingByPeaga.ipa

          echo "=== TAMANHO FINAL ==="
          ls -lh FloatingByPeaga.ipa

          rm -rf Payload

      - name: Enviar IPA
        uses: actions/upload-artifact@v4
        with:
          name: FloatingByPeaga-IPA
          path: FloatingByPeaga.ipa
